import {
  AlertCircle,
  ArrowRight,
  Building2,
  Calendar,
  Check,
  ChevronLeft,
  ChevronRight,
  Columns3,
  Copy,
  CreditCard,
  DollarSign,
  Edit,
  Eye,
  File,
  FileText,
  HelpCircle,
  Home,
  Image,
  Laptop,
  List,
  Loader2,
  LogOut,
  Moon,
  MoreVertical,
  Package,
  Plus,
  Settings,
  SunMedium,
  Trash,
  Truck,
  User,
  Users,
  X,
} from 'lucide-react'

export const Icons = {
  logo: Package,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  plus: Plus,
  warning: AlertCircle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Package,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  home: Home,
  building: Building2,
  users: Users,
  dollarSign: DollarSign,
  truck: Truck,
  calendar: Calendar,
  logout: LogOut,
  copy: Copy,
  check: Check,
  list: List,
  kanban: Columns3,
  package: Package,
  eye: Eye,
  edit: Edit,
  microsoft: (props: any) => (
    <svg role="img" viewBox="0 0 24 24" {...props}>
      <path
        fill="currentColor"
        d="M11.4 24H0V12.6h11.4V24zM24 24H12.6V12.6H24V24zM11.4 11.4H0V0h11.4v11.4zM24 11.4H12.6V0H24v11.4z"
      />
    </svg>
  ),
}